version="2.0"
company="viewzr"
os="Fedora"
distro="25"

Vagrant.configure("2") do |config|
  config.vm.hostname = "#{company}-dev"
  config.vm.box      = "ubuntu/xenial64"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory      = 4096
    vb.cpus        = 2
    vb.name        = "#{company}-#{version}-dev-#{os}-#{distro}"
    vb.gui         = true
  end
end
