version="2.0"
company="viewzr"
os="Fedora"
distro="25"

Vagrant.configure("2") do |config|
  config.vm.hostname = "#{company}-dev"
  config.vm.box      = "file://./packer/box/virtualbox/#{company}-#{version}-#{os}#{distro}-dev.box"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
    vb.memory      = 4096
    vb.cpus        = 2
    vb.name        = "#{company}-#{version}-#{os}#{distro}-dev"
    vb.gui         = true
  end

  config.vm.provision "shell", run: "always" do |shell|
    shell.inline = "(sudo cp /vagrant/bin/* /usr/local/bin/)"
  end

  config.vm.provision "shell" run: "always" do |shell|
    shell.inline = "(sudo cp /vagrant/share/* /usr/local/share/)"
  end
end
